apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: replicaset-mypod
spec:
  selector:
    matchLabels:
      app: front
  replicas: 6
  template:
    metadata:
      name: my-pod-front
      labels:
        app: front
    spec:
      containers:
        - name: my-pod-nginx
          image: nginx