apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-webapp
  labels:
    app: App1
    function: front-end
spec:
  replicas: 3
  selector:
    app: App1
    function: front-end
  template:
    metadata:
      name: simple-webapp
      labels:
        app: App1
        function: front-end
    spec:
      containers:
        - name: simple-webapp
          image: simple-webapp
          ports:
            - containerPort: 8080
